### PR TITLE
move code around and split sensors

### PR DESCRIPTION
**Pull request by profawk**
this splits up the temp sensor code and splits it up so it's easier to add more sensors (e.g. BME280)

### CODE REVIEW

**Comment by mp-se** [comment]
Thanks, I will take a look at this when I'm back from vacation.

**Comment by mp-se** [comment]
Hi!

Thanks for your contribution but before I can integrate it I would like to have the following changes:

* reset() function should be applied to all temperature sensors and not just DHT. That should to a power on/off independent of which sensor is used, this can be moved to the base class. 
* Before every call to the sensor object add a check if this is NULL so we don't get unexpected crashes if memory allocation fails. 
* The above point also applies to the dynamically allocated objects in the specific sensor types. 
* I would suggest that you also use the "tempReading" class in the TempHumidity to store the last read values, this will be more consistent and easier to add other types of data to that structure.

**Comment by profawk** [comment]
regarding 4, I just use the struct to carry more then 1 value. I'm not really sure I understand what you mean

**Comment by profawk** [comment]
also, I am lacking the hardware to test this. I don't have a DHT or a DS18B20. I just wanted to help out if possible :)

**Comment by mp-se** [comment]
> also, I am lacking the hardware to test this. I don't have a DHT or a DS18B20. I just wanted to help out if possible :) So I would love if you could make sure this works as expected!

No problems, i can test it later. 

On point 4,

in the temphumidity class data is stored as two floats, this could be replaced with your struct instead. Not a big deal i can fix that when i merge and test it.

**Comment by profawk** [comment]
understood, fixed :)

**Comment by mp-se** [comment]
I've now merged your code into the dev branch, thanks for the PR.

**Comment by mp-se** [comment]
@profawk just noticed that the codes does not compile on esp32 target, looks like the "make_unique" is not implemented on that compiler version. `

I guess the best option is to refactor the code so it can be complied. ?

**Comment by profawk** [comment]
this git diff should solve it, 
[c++11_diff.txt](https://github.com/mp-se/kegmon/files/12283330/c%2B%2B11_diff.txt)
use `git apply c++11_diff.txt`

**Comment by profawk** [comment]
btw, the compiler supports up to c++23 but arduino framework limits it to c++11 for some reason

**Comment by mp-se** [comment]
Strange indeed, that the newer version (esp32) does not support it but the older one does.  Well its not a big deal to adjust for it. But it was a good learning experience, i have not been working as a developer for the last 10 years so I'm not really up to date on all the new additions to the language.

**Comment by profawk** [comment]
I want to add support for BME280. is it ok if I bring back the unique_ptr? I will make it work for esp32

**Comment by mp-se** [comment]
Yes, If you can make it work

**Pull request merged**
